apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-statefulset.fullname" . }}
  labels:
    {{- include "nginx-statefulset.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "nginx-statefulset.selectorLabels" . | nindent 4 }}
