apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nginx-statefulset.fullname" . }}
  labels:
    {{- include "nginx-statefulset.labels" . | nindent 4 }}
  annotations:
    date-time: {{ now | quote }}
spec:
  serviceName: {{ include "nginx-statefulset.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-statefulset.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-statefulset.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-persistent-storage
              mountPath: /var/www/html
  volumeClaimTemplates:
    - metadata:
        name: nginx-persistent-storage
        labels:
          app: {{ include "nginx-statefulset.name" . }}
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        storageClassName: {{ .Values.persistence.storageClassName }}
